apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  namespace: mm
spec:
  replicas: 1
  selector:
    app: frontend
  template:
    metadata:
      name: frontend
      namespace: mm
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: joxxorr/frontend:latest      
          imagePullPolicy: Always